[package]
name = "molecule-codegen"
version = "0.4.2"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "Code generator for molecule."
homepage = "https://github.com/nervosnetwork/molecule"
repository = "https://github.com/nervosnetwork/molecule"
keywords = ["molecule", "code-generation", "serialization"]
categories = [
    "parser-implementations",
    "development-tools::build-utils",
    "encoding",
    "data-structures"
]
license = "MIT"

[dependencies]
molecule = { version = "=0.4.0", path = "../../bindings/rust", default-features = false }
pest = "~2.1"
pest_derive = "~2.1"
quote = "~1.0"
proc-macro2 = "~1.0"
case = "~1.0"
same-file = "~1.0"
semver = "~0.9"

[badges]
maintenance = { status = "experimental" }
